In [2]:
import numpy as np
np.empty((2,3,4), dtype = np.int64)

array([[[23925768161198147, 32370111954616435, 29555319238754396,
          9007650233385077],
        [29273818492371027, 19984860791767154, 29273891506421864,
         27303545193693276],
        [28147970124742755, 30399692625084513, 32370017465139305,
         12666807751278697]],

       [[30118247716159600, 32370056120172641, 30681274979844188,
         32088542489935984],
        [31244151918821473, 32370030349647981, 14636930723676262,
         14355704855068718],
        [29555383658676280, 30681189079515246, 12948072270528612,
              429504659568]]], dtype=int64)

In [3]:
np.arange(0,2,0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [5]:
np.linspace(0,2,10)

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [7]:
x = np.linspace(0,2*np.pi,100)
y = np.sin(x)
y

array([ 0.00000000e+00,  6.34239197e-02,  1.26592454e-01,  1.89251244e-01,
        2.51147987e-01,  3.12033446e-01,  3.71662456e-01,  4.29794912e-01,
        4.86196736e-01,  5.40640817e-01,  5.92907929e-01,  6.42787610e-01,
        6.90079011e-01,  7.34591709e-01,  7.76146464e-01,  8.14575952e-01,
        8.49725430e-01,  8.81453363e-01,  9.09631995e-01,  9.34147860e-01,
        9.54902241e-01,  9.71811568e-01,  9.84807753e-01,  9.93838464e-01,
        9.98867339e-01,  9.99874128e-01,  9.96854776e-01,  9.89821442e-01,
        9.78802446e-01,  9.63842159e-01,  9.45000819e-01,  9.22354294e-01,
        8.95993774e-01,  8.66025404e-01,  8.32569855e-01,  7.95761841e-01,
        7.55749574e-01,  7.12694171e-01,  6.66769001e-01,  6.18158986e-01,
        5.67059864e-01,  5.13677392e-01,  4.58226522e-01,  4.00930535e-01,
        3.42020143e-01,  2.81732557e-01,  2.20310533e-01,  1.58001396e-01,
        9.50560433e-02,  3.17279335e-02, -3.17279335e-02, -9.50560433e-02,
       -1.58001396e-01, -

In [9]:
l = []
for x in [1,2,3,4,5]:
    l.append(x*x)
l

[1, 4, 9, 16, 25]

In [10]:
a = np.array([20,30,40,50])
b = np.arange( 4 )
a,b

(array([20, 30, 40, 50]), array([0, 1, 2, 3]))

In [12]:
c = a-b
c

array([20, 29, 38, 47])

In [13]:
f = [1,2,8,6]
g = [4,8,6,2]
print(f-g)

TypeError: unsupported operand type(s) for -: 'list' and 'list'

In [14]:
b**3

array([ 0,  1,  8, 27], dtype=int32)

In [15]:
10*np.sin(a)   #First [sin(20),sin(30),..] --> [10*sin(20), 10*sin(30),...]

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [16]:
a<35 # Compare each a[i] with 35 and give True/false

array([ True,  True, False, False])

Can we "filter an array"? i.e return the actual subarray with values < 35?

In [17]:
A = np.array([[1,1]],[[0,1]])
B = np.array([[2,0]],[[3,4]])

TypeError: Field elements must be 2- or 3-tuples, got '[0, 1]'