# Numpy Package 

Indexing and Slicing 

In [3]:
import numpy as np
a = np.arange(0,10,1)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
def f(x,y):
    return(10*x + y)

In [8]:
b = np.fromfunction(f,(5,4), dtype =int)
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [9]:
print(b)

[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]


Iterating over elements

In [7]:
for row in b:
    print(row)     #Print is just a representation 

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [12]:
for element in b.flat:
    print(element, end = " ")

0 1 2 3 10 11 12 13 20 21 22 23 30 31 32 33 40 41 42 43 

## Stacking arrays

In [ ]:
a = np.floor(10*np.random.random)

## Copy and View 

In [13]:
c = a.copy()   #Created a disjoint copy of the array (Deep Copy)
d = a.view()   #Creates same copy of the array (shallow copy)


## Import Pandas


In [14]:
import pandas as pd

In [16]:
h = ('AA' , '2012-02-01', 100 , 10.2)
s = pd.Series(h)
type(s)

pandas.core.series.Series

In [17]:
s

0            AA
1    2012-02-01
2           100
3          10.2
dtype: object

In [26]:
d = {'name': 'IBM' , 'date': '2012-02-01', 'Shares': 100, 'Price': 10.2}
ds = pd.Series(d, index = ['name', 'date', 'Shares','Price'])
type(ds)

pandas.core.series.Series

In [27]:
ds

name             IBM
date      2012-02-01
Shares           100
Price           10.2
dtype: object

## Creating an Index 

In [28]:
 ds['Shares']

100

In [29]:
ds[[0,2]]

name      IBM
Shares    100
dtype: object

In [31]:
ds[0:2]

name           IBM
date    2012-02-01
dtype: object

In [32]:
ds['name':'Shares']

name             IBM
date      2012-02-01
Shares           100
dtype: object

In [34]:
data1 = [ ['AA','IBM', 'Google'], ['1','2','3'],[100,30,90],[ 12.9,12.5,75.2]]
df1 = pd.DataFrame(data1)

In [41]:
df1

0     1       2    Owner
0    AA   IBM  Google  Unknown
1     1     2       3  Unknown
2   100    30      90  Unknown
3  12.9  12.5    75.2  Unknown

In [43]:
data2 = { 'Name':['AA','IBM', 'Google'],
           'Date': ['1','2','3'],
           'Shares':[100,30,90],
           'Price' : [ 12.9,12.5,75.2]}

In [45]:
df2 = pd.DataFrame(data2)

In [46]:
df2

Name Date  Shares  Price
0      AA    1     100   12.9
1     IBM    2      30   12.5
2  Google    3      90   75.2

## Add a column 

In [47]:
df2['Owner'] = 'Unknown'

In [48]:
df2

Name Date  Shares  Price    Owner
0      AA    1     100   12.9  Unknown
1     IBM    2      30   12.5  Unknown
2  Google    3      90   75.2  Unknown

In [51]:
df2.index = ['One' , 'Two' ,'Three']
df2

Name Date  Shares  Price    Owner
One        AA    1     100   12.9  Unknown
Two       IBM    2      30   12.5  Unknown
Three  Google    3      90   75.2  Unknown